# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZL_4jCaIi_ZacGVNGqtUqtRYTfGNMrb
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %%writefile matrix_mul.cu
# 
# #include <stdio.h>
# #include <cuda_runtime.h>
# 
# __global__ void matrixMul(int *A, int *B, int *C)
# {
#     int row = threadIdx.y;
#     int col = threadIdx.x;
# 
#     int sum = 0;
# 
#     for(int k = 0; k < 2; k++)
#     {
#         sum += A[row * 2 + k] * B[k * 2 + col];
#     }
# 
#     C[row * 2 + col] = sum;
# }
# 
# int main()
# {
#     int h_A[4] = {1, 2,
#                   3, 4};
# 
#     int h_B[4] = {5, 6,
#                   7, 8};
# 
#     int h_C[4];
# 
#     int *d_A, *d_B, *d_C;
# 
#     cudaMalloc((void**)&d_A, 4 * sizeof(int));
#     cudaMalloc((void**)&d_B, 4 * sizeof(int));
#     cudaMalloc((void**)&d_C, 4 * sizeof(int));
# 
#     cudaMemcpy(d_A, h_A, 4 * sizeof(int), cudaMemcpyHostToDevice);
#     cudaMemcpy(d_B, h_B, 4 * sizeof(int), cudaMemcpyHostToDevice);
# 
#     dim3 threads(2, 2);
# 
#     matrixMul<<<1, threads>>>(d_A, d_B, d_C);
# 
#     cudaMemcpy(h_C, d_C, 4 * sizeof(int), cudaMemcpyDeviceToHost);
# 
#     printf("Matrix Multiplication Result:\n");
# 
#     for(int i = 0; i < 4; i++)
#     {
#         printf("%d ", h_C[i]);
# 
#         if((i + 1) % 2 == 0)
#             printf("\n");
#     }
# 
#     cudaFree(d_A);
#     cudaFree(d_B);
#     cudaFree(d_C);
# 
#     return 0;
# }

!nvcc -o matrix_mul matrix_mul.cu

!./matrix_mul

