# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105OBWaOvpH8InMHAQbNukJB9D0rOvPRe
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile reduction.cpp
# 
# #include <iostream>
# #include <omp.h>
# #include <climits>
# 
# using namespace std;
# 
# // Minimum Reduction
# void min_reduction(int arr[], int n)
# {
#     int min_value = INT_MAX;
# 
#     #pragma omp parallel for reduction(min:min_value)
#     for(int i = 0; i < n; i++)
#     {
#         if(arr[i] < min_value)
#         {
#             min_value = arr[i];
#         }
#     }
# 
#     cout << "Minimum Value = " << min_value << endl;
# }
# 
# // Maximum Reduction
# void max_reduction(int arr[], int n)
# {
#     int max_value = INT_MIN;
# 
#     #pragma omp parallel for reduction(max:max_value)
#     for(int i = 0; i < n; i++)
#     {
#         if(arr[i] > max_value)
#         {
#             max_value = arr[i];
#         }
#     }
# 
#     cout << "Maximum Value = " << max_value << endl;
# }
# 
# // Sum Reduction
# void sum_reduction(int arr[], int n)
# {
#     int sum = 0;
# 
#     #pragma omp parallel for reduction(+:sum)
#     for(int i = 0; i < n; i++)
#     {
#         sum += arr[i];
#     }
# 
#     cout << "Sum = " << sum << endl;
# }
# 
# // Average Reduction
# void average_reduction(int arr[], int n)
# {
#     int sum = 0;
# 
#     #pragma omp parallel for reduction(+:sum)
#     for(int i = 0; i < n; i++)
#     {
#         sum += arr[i];
#     }
# 
#     double average = (double)sum / n;
# 
#     cout << "Average = " << average << endl;
# }
# 
# int main()
# {
#     int n;
# 
#     cout << "Enter total number of elements: ";
#     cin >> n;
# 
#     int *arr = new int[n];
# 
#     cout << "Enter array elements:\n";
# 
#     for(int i = 0; i < n; i++)
#     {
#         cin >> arr[i];
#     }
# 
#     min_reduction(arr, n);
#     max_reduction(arr, n);
#     sum_reduction(arr, n);
#     average_reduction(arr, n);
# 
#     delete[] arr;
# 
#     return 0;
# }

!g++ -fopenmp reduction.cpp -o reduction

!./reduction