# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmEE2EBzUKNQaxcykCk19kiYYNeh3Uyt
"""

!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vector_add.cu
# 
# #include <stdio.h>
# #include <cuda_runtime.h>
# 
# __global__ void vectorAdd(int *a, int *b, int *c)
# {
#     int id = threadIdx.x;
#     c[id] = a[id] + b[id];
# }
# 
# int main()
# {
#     int h_a[5] = {1, 2, 3, 4, 5};
#     int h_b[5] = {5, 4, 3, 2, 1};
#     int h_c[5];
# 
#     int *d_a, *d_b, *d_c;
# 
#     cudaMalloc((void**)&d_a, 5 * sizeof(int));
#     cudaMalloc((void**)&d_b, 5 * sizeof(int));
#     cudaMalloc((void**)&d_c, 5 * sizeof(int));
# 
#     cudaMemcpy(d_a, h_a, 5 * sizeof(int), cudaMemcpyHostToDevice);
#     cudaMemcpy(d_b, h_b, 5 * sizeof(int), cudaMemcpyHostToDevice);
# 
#     vectorAdd<<<1, 5>>>(d_a, d_b, d_c);
# 
#     cudaMemcpy(h_c, d_c, 5 * sizeof(int), cudaMemcpyDeviceToHost);
# 
#     printf("Vector Addition Result:\n");
# 
#     for(int i = 0; i < 5; i++)
#     {
#         printf("%d ", h_c[i]);
#     }
# 
#     cudaFree(d_a);
#     cudaFree(d_b);
#     cudaFree(d_c);
# 
#     return 0;
# }

!nvcc vector_add.cu -o vector_add

!./vector_add